version: '3.1'

services:
  postgresql:
    image: ${POSTGRES_IMAGE}
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  app:
    image: ${TEST_IMAGE}
    tty: true
